using DockeLib.Data;
using Newtonsoft.Json;

namespace DockeLib
{
    public class OkeiReader
    {
        public static List<OkeiEntry> ReadOkeiEntries()
        {
            try
            {
                
                return OkeiJson.ListValues;
            }
            catch (Exception ex)
            {
                throw new Exception($"Error reading OKEI JSON file: {ex.Message}");
            }
        }
    }

    public static class OkeiJson
    {
        public static readonly List<OkeiEntry> ListValues = new List<OkeiEntry>
        {
            new OkeiEntry { Code = "354", Name = "Секунда", ShortName = "с", CodeName = "С" },
new OkeiEntry { Code = "355", Name = "Минута", ShortName = "мин", CodeName = "МИН" },
new OkeiEntry { Code = "356", Name = "Час", ShortName = "ч", CodeName = "Ч" },
new OkeiEntry { Code = "359", Name = "Сутки", ShortName = "сут; дн", CodeName = "СУТ; ДН" },
new OkeiEntry { Code = "360", Name = "Неделя", ShortName = "нед", CodeName = "НЕД" },
new OkeiEntry { Code = "361", Name = "Декада", ShortName = "дек", CodeName = "ДЕК" },
new OkeiEntry { Code = "362", Name = "Месяц", ShortName = "мес", CodeName = "МЕС" },
new OkeiEntry { Code = "364", Name = "Квартал", ShortName = "кварт", CodeName = "КВАРТ" },
new OkeiEntry { Code = "365", Name = "Полугодие", ShortName = "полгода", CodeName = "ПОЛГОД" },
new OkeiEntry { Code = "366", Name = "Год", ShortName = "г; лет", CodeName = "ГОД; ЛЕТ" },
new OkeiEntry { Code = "368", Name = "Десятилетие", ShortName = "деслет", CodeName = "ДЕСЛЕТ" },
new OkeiEntry { Code = "003", Name = "Миллиметр", ShortName = "мм", CodeName = "ММ" },
new OkeiEntry { Code = "004", Name = "Сантиметр", ShortName = "см", CodeName = "СМ" },
new OkeiEntry { Code = "005", Name = "Дециметр", ShortName = "дм", CodeName = "ДМ" },
new OkeiEntry { Code = "006", Name = "Метр", ShortName = "м", CodeName = "М" },
new OkeiEntry { Code = "008", Name = "Километр; тысяча метров", ShortName = "км; 103 м", CodeName = "КМ; ТЫС М" },
new OkeiEntry { Code = "009", Name = "Мегаметр; миллион метров", ShortName = "Мм; 106 м", CodeName = "МЕГАМ; МЛН М" },
new OkeiEntry { Code = "039", Name = "Дюйм (25,4 мм)", ShortName = "дюйм", CodeName = "ДЮЙМ" },
new OkeiEntry { Code = "041", Name = "Фут (0,3048 м)", ShortName = "фут", CodeName = "ФУТ" },
new OkeiEntry { Code = "043", Name = "Ярд (0,9144 м)", ShortName = "ярд", CodeName = "ЯРД" },
new OkeiEntry { Code = "047", Name = "Морская миля (1852 м)", ShortName = "миля", CodeName = "МИЛЬ" },
new OkeiEntry { Code = "160", Name = "Гектограмм", ShortName = "гг", CodeName = "ГГ" },
new OkeiEntry { Code = "161", Name = "Миллиграмм", ShortName = "мг", CodeName = "МГ" },
new OkeiEntry { Code = "162", Name = "Метрический карат", ShortName = "кар", CodeName = "КАР" },
new OkeiEntry { Code = "163", Name = "Грамм", ShortName = "г", CodeName = "Г" },
new OkeiEntry { Code = "164", Name = "Микрограмм", ShortName = "мкг", CodeName = "МКГ" },
new OkeiEntry { Code = "166", Name = "Килограмм", ShortName = "кг", CodeName = "КГ" },
new OkeiEntry { Code = "168", Name = "Тонна; метрическая тонна (1000 кг)", ShortName = "т", CodeName = "Т" },
new OkeiEntry { Code = "170", Name = "Килотонна", ShortName = "103 т", CodeName = "КТ" },
new OkeiEntry { Code = "173", Name = "Сантиграмм", ShortName = "сг", CodeName = "СГ" },
new OkeiEntry { Code = "181", Name = "Брутто-регистровая тонна (2,8316 м3)", ShortName = "БРТ", CodeName = "БРУТТ. РЕГИСТР Т" },
new OkeiEntry { Code = "185", Name = "Грузоподъемность в метрических тоннах", ShortName = "т грп", CodeName = "Т ГРУЗОПОД" },
new OkeiEntry { Code = "206", Name = "Центнер (метрический) (100 кг); гектокилограмм; квинтал1 (метрический); децитонна", ShortName = "ц", CodeName = "Ц" },
new OkeiEntry { Code = "110", Name = "Кубический миллиметр", ShortName = "мм3", CodeName = "ММ3" },
new OkeiEntry { Code = "111", Name = "Кубический сантиметр; миллилитр", ShortName = "см3; мл", CodeName = "СМ3; МЛ" },
new OkeiEntry { Code = "112", Name = "Литр; кубический дециметр", ShortName = "л; дм3", CodeName = "Л; ДМ3" },
new OkeiEntry { Code = "113", Name = "Кубический метр", ShortName = "м3", CodeName = "М3" },
new OkeiEntry { Code = "118", Name = "Децилитр", ShortName = "дл", CodeName = "ДЛ" },
new OkeiEntry { Code = "122", Name = "Гектолитр", ShortName = "гл", CodeName = "ГЛ" },
new OkeiEntry { Code = "126", Name = "Мегалитр", ShortName = "Мл", CodeName = "МЕГАЛ" },
new OkeiEntry { Code = "131", Name = "Кубический дюйм (16387,1 мм3)", ShortName = "дюйм3", CodeName = "ДЮЙМ3" },
new OkeiEntry { Code = "132", Name = "Кубический фут (0,02831685 м3)", ShortName = "фут3", CodeName = "ФУТ3" },
new OkeiEntry { Code = "133", Name = "Кубический ярд (0,764555 м3)", ShortName = "ярд3", CodeName = "ЯРД3" },
new OkeiEntry { Code = "159", Name = "Миллион кубических метров", ShortName = "106 м3", CodeName = "МЛН М3" },
new OkeiEntry { Code = "050", Name = "Квадратный миллиметр", ShortName = "мм2", CodeName = "ММ2" },
new OkeiEntry { Code = "051", Name = "Квадратный сантиметр", ShortName = "см2", CodeName = "СМ2" },
new OkeiEntry { Code = "053", Name = "Квадратный дециметр", ShortName = "дм2", CodeName = "ДМ2" },
new OkeiEntry { Code = "055", Name = "Квадратный метр", ShortName = "м2", CodeName = "М2" },
new OkeiEntry { Code = "058", Name = "Тысяча квадратных метров", ShortName = "103 м2", CodeName = "ТЫС М2" },
new OkeiEntry { Code = "059", Name = "Гектар", ShortName = "га", CodeName = "ГА" },
new OkeiEntry { Code = "061", Name = "Квадратный километр", ShortName = "км2", CodeName = "КМ2" },
new OkeiEntry { Code = "071", Name = "Квадратный дюйм (645,16 мм2)", ShortName = "дюйм2", CodeName = "ДЮЙМ2" },
new OkeiEntry { Code = "073", Name = "Квадратный фут (0,092903 м2)", ShortName = "фут2", CodeName = "ФУТ2" },
new OkeiEntry { Code = "075", Name = "Квадратный ярд (0,8361274 м2)", ShortName = "ярд2", CodeName = "ЯРД2" },
new OkeiEntry { Code = "109", Name = "Ар (100 м2)", ShortName = "а", CodeName = "АР" },
new OkeiEntry { Code = "212", Name = "Ватт", ShortName = "Вт", CodeName = "ВТ" },
new OkeiEntry { Code = "214", Name = "Киловатт", ShortName = "кВт", CodeName = "КВТ" },
new OkeiEntry { Code = "215", Name = "Мегаватт; тысяча киловатт", ShortName = "МВт; 103 кВт", CodeName = "МЕГАВТ; ТЫС КВТ" },
new OkeiEntry { Code = "222", Name = "Вольт", ShortName = "В", CodeName = "В" },
new OkeiEntry { Code = "223", Name = "Киловольт", ShortName = "кВ", CodeName = "КВ" },
new OkeiEntry { Code = "227", Name = "Киловольт-ампер", ShortName = "кВ.А", CodeName = "КВ.А" },
new OkeiEntry { Code = "228", Name = "Мегавольт-ампер (тысяча киловольт-ампер)", ShortName = "МВ.А", CodeName = "МЕГАВ.А" },
new OkeiEntry { Code = "230", Name = "Киловар", ShortName = "квар", CodeName = "КВАР" },
new OkeiEntry { Code = "243", Name = "Ватт-час", ShortName = "Вт.ч", CodeName = "ВТ.Ч" },
new OkeiEntry { Code = "245", Name = "Киловатт-час", ShortName = "кВт.ч", CodeName = "КВТ.Ч" },
new OkeiEntry { Code = "246", Name = "Мегаватт-час; 1000 киловатт-часов", ShortName = "МВт.ч; 103 кВт.ч", CodeName = "МЕГАВТ.Ч; ТЫС КВТ.Ч" },
new OkeiEntry { Code = "247", Name = "Гигаватт-час (миллион киловатт-часов)", ShortName = "ГВт.ч", CodeName = "ГИГАВТ.Ч" },
new OkeiEntry { Code = "260", Name = "Ампер", ShortName = "А", CodeName = "А" },
new OkeiEntry { Code = "263", Name = "Ампер-час (3,6 кКл)", ShortName = "А.ч", CodeName = "А.Ч" },
new OkeiEntry { Code = "264", Name = "Тысяча ампер-часов", ShortName = "103 А.ч", CodeName = "ТЫС А.Ч" },
new OkeiEntry { Code = "270", Name = "Кулон", ShortName = "Кл", CodeName = "КЛ" },
new OkeiEntry { Code = "271", Name = "Джоуль", ShortName = "Дж", CodeName = "ДЖ" },
new OkeiEntry { Code = "273", Name = "Килоджоуль", ShortName = "кДж", CodeName = "КДЖ" },
new OkeiEntry { Code = "274", Name = "Ом", ShortName = "Ом", CodeName = "ОМ" },
new OkeiEntry { Code = "280", Name = "Градус Цельсия", ShortName = "град. C", CodeName = "ГРАД ЦЕЛЬС" },
new OkeiEntry { Code = "281", Name = "Градус Фаренгейта", ShortName = "град. F", CodeName = "ГРАД ФАРЕНГ" },
new OkeiEntry { Code = "282", Name = "Кандела", ShortName = "кд", CodeName = "КД" },
new OkeiEntry { Code = "283", Name = "Люкс", ShortName = "лк", CodeName = "ЛК" },
new OkeiEntry { Code = "284", Name = "Люмен", ShortName = "лм", CodeName = "ЛМ" },
new OkeiEntry { Code = "288", Name = "Кельвин", ShortName = "K", CodeName = "К" },
new OkeiEntry { Code = "289", Name = "Ньютон", ShortName = "Н", CodeName = "Н" },
new OkeiEntry { Code = "290", Name = "Герц", ShortName = "Гц", CodeName = "ГЦ" },
new OkeiEntry { Code = "291", Name = "Килогерц", ShortName = "кГц", CodeName = "КГЦ" },
new OkeiEntry { Code = "292", Name = "Мегагерц", ShortName = "МГц", CodeName = "МЕГАГЦ" },
new OkeiEntry { Code = "294", Name = "Паскаль", ShortName = "Па", CodeName = "ПА" },
new OkeiEntry { Code = "296", Name = "Сименс", ShortName = "См", CodeName = "СИ" },
new OkeiEntry { Code = "297", Name = "Килопаскаль", ShortName = "кПа", CodeName = "КПА" },
new OkeiEntry { Code = "298", Name = "Мегапаскаль", ShortName = "МПа", CodeName = "МЕГАПА" },
new OkeiEntry { Code = "300", Name = "Физическая атмосфера (101325 Па)", ShortName = "атм", CodeName = "АТМ" },
new OkeiEntry { Code = "301", Name = "Техническая атмосфера (98066,5 Па)", ShortName = "ат", CodeName = "АТТ" },
new OkeiEntry { Code = "302", Name = "Гигабеккерель", ShortName = "ГБк", CodeName = "ГИГАБК" },
new OkeiEntry { Code = "303", Name = "Килобеккерель", ShortName = "кБк", CodeName = "КИЛОБК" },
new OkeiEntry { Code = "304", Name = "Милликюри", ShortName = "мКи", CodeName = "МКИ" },
new OkeiEntry { Code = "305", Name = "Кюри", ShortName = "Ки", CodeName = "КИ" },
new OkeiEntry { Code = "306", Name = "Грамм делящихся изотопов", ShortName = "г Д/И", CodeName = "Г ДЕЛЯЩ ИЗОТОП" },
new OkeiEntry { Code = "307", Name = "Мегабеккерель", ShortName = "МБк", CodeName = "МЕГАБК" },
new OkeiEntry { Code = "308", Name = "Миллибар", ShortName = "мб", CodeName = "МБАР" },
new OkeiEntry { Code = "309", Name = "Бар", ShortName = "бар", CodeName = "БАР" },
            new OkeiEntry { Code = "310", Name = "Гектобар", ShortName = "гб", CodeName = "ГБАР" },
            new OkeiEntry { Code = "312", Name = "Килобар", ShortName = "кб", CodeName = "КБАР" },
            new OkeiEntry { Code = "314", Name = "Фарад", ShortName = "Ф", CodeName = "Ф" },
            new OkeiEntry { Code = "316", Name = "Килограмм на кубический метр", ShortName = "кг/м3", CodeName = "КГ/М3" },
            new OkeiEntry { Code = "320", Name = "Моль", ShortName = "моль", CodeName = "МОЛЬ" },
            new OkeiEntry { Code = "323", Name = "Беккерель", ShortName = "Бк", CodeName = "БК" },
            new OkeiEntry { Code = "324", Name = "Вебер", ShortName = "Вб", CodeName = "ВБ" },
            new OkeiEntry { Code = "327", Name = "Узел (миля/ч)", ShortName = "уз", CodeName = "УЗ" },
            new OkeiEntry { Code = "328", Name = "Метр в секунду", ShortName = "м/с", CodeName = "М/С" },
            new OkeiEntry { Code = "330", Name = "Оборот в секунду", ShortName = "об/с", CodeName = "ОБ/С" },
            new OkeiEntry { Code = "331", Name = "Оборот в минуту", ShortName = "об/мин", CodeName = "ОБ/МИН" },
            new OkeiEntry { Code = "333", Name = "Километр в час", ShortName = "км/ч", CodeName = "КМ/Ч" },
            new OkeiEntry { Code = "335", Name = "Метр на секунду в квадрате", ShortName = "м/с2", CodeName = "М/С2" },
            new OkeiEntry { Code = "349", Name = "Кулон на килограмм", ShortName = "Кл/кг", CodeName = "КЛ/КГ" },
            new OkeiEntry { Code = "499", Name = "Килограмм в секунду", ShortName = "кг/с", CodeName = "КГ/С" },
            new OkeiEntry { Code = "533", Name = "Тонна пара в час", ShortName = "т пар/ч", CodeName = "Т ПАР/Ч" },
            new OkeiEntry { Code = "596", Name = "Кубический метр в секунду", ShortName = "м3/с", CodeName = "М3/С" },
            new OkeiEntry { Code = "598", Name = "Кубический метр в час", ShortName = "м3/ч", CodeName = "М3/Ч" },
            new OkeiEntry { Code = "599", Name = "Тысяча кубических метров в сутки", ShortName = "103 м3/сут", CodeName = "ТЫС М3/СУТ" },
            new OkeiEntry { Code = "616", Name = "Бобина", ShortName = "боб", CodeName = "БОБ" },
            new OkeiEntry { Code = "625", Name = "Лист", ShortName = "л.", CodeName = "ЛИСТ" },
            new OkeiEntry { Code = "626", Name = "Сто листов", ShortName = "100 л.", CodeName = "100 ЛИСТ" },
            new OkeiEntry { Code = "630", Name = "Тысяча стандартных условных кирпичей", ShortName = "тыс станд. усл. кирп", CodeName = "ТЫС СТАНД УСЛ КИРП" },
            new OkeiEntry { Code = "641", Name = "Дюжина (12 шт.)", ShortName = "дюжина", CodeName = "ДЮЖИНА" },
            new OkeiEntry { Code = "657", Name = "Изделие", ShortName = "изд", CodeName = "ИЗД" },
            new OkeiEntry { Code = "683", Name = "Сто ящиков", ShortName = "100 ящ.", CodeName = "100 ЯЩ" },
            new OkeiEntry { Code = "704", Name = "Набор", ShortName = "набор", CodeName = "НАБОР" },
            new OkeiEntry { Code = "715", Name = "Пара (2 шт.)", ShortName = "пар", CodeName = "ПАР" },
            new OkeiEntry { Code = "730", Name = "Два десятка", ShortName = "20", CodeName = "2 ДЕС" },
            new OkeiEntry { Code = "732", Name = "Десять пар", ShortName = "10 пар", CodeName = "ДЕС ПАР" },
            new OkeiEntry { Code = "733", Name = "Дюжина пар", ShortName = "дюжина пар", CodeName = "ДЮЖИНА ПАР" },
            new OkeiEntry { Code = "734", Name = "Посылка", ShortName = "посыл", CodeName = "ПОСЫЛ" },
            new OkeiEntry { Code = "735", Name = "Часть", ShortName = "часть", CodeName = "ЧАСТЬ" },
            new OkeiEntry { Code = "736", Name = "Рулон", ShortName = "рул", CodeName = "РУЛ" },
            new OkeiEntry { Code = "737", Name = "Дюжина рулонов", ShortName = "дюжина рул", CodeName = "ДЮЖИНА РУЛ" },
            new OkeiEntry { Code = "740", Name = "Дюжина штук", ShortName = "дюжина шт", CodeName = "ДЮЖИНА ШТ" },
            new OkeiEntry { Code = "745", Name = "Элемент", ShortName = "элем", CodeName = "ЭЛЕМ" },
            new OkeiEntry { Code = "778", Name = "Упаковка", ShortName = "упак", CodeName = "УПАК" },
            new OkeiEntry { Code = "780", Name = "Дюжина упаковок", ShortName = "дюжина упак", CodeName = "ДЮЖИНА УПАК" },
            new OkeiEntry { Code = "781", Name = "Сто упаковок", ShortName = "100 упак", CodeName = "100 УПАК" },
            new OkeiEntry { Code = "796", Name = "Штука", ShortName = "шт", CodeName = "ШТ" },
            new OkeiEntry { Code = "797", Name = "Сто штук", ShortName = "100 шт", CodeName = "100 ШТ" },
            new OkeiEntry { Code = "798", Name = "Тысяча штук", ShortName = "тыс. шт; 1000 шт", CodeName = "ТЫС ШТ" },
            new OkeiEntry { Code = "799", Name = "Миллион штук", ShortName = "106 шт", CodeName = "МЛН ШТ" },
            new OkeiEntry { Code = "800", Name = "Миллиард штук", ShortName = "109 шт", CodeName = "МЛРД ШТ" },
            new OkeiEntry { Code = "801", Name = "Биллион штук (Европа); триллион штук", ShortName = "1012 шт", CodeName = "БИЛЛ ШТ (ЕВР); ТРИЛЛ ШТ" },
            new OkeiEntry { Code = "802", Name = "Квинтильон штук (Европа)", ShortName = "1018 шт", CodeName = "КВИНТ ШТ" },
            new OkeiEntry { Code = "820", Name = "Крепость спирта по массе", ShortName = "креп. спирта по массе", CodeName = "КРЕП СПИРТ ПО МАССЕ" },
            new OkeiEntry { Code = "821", Name = "Крепость спирта по объему", ShortName = "креп. спирта по объему", CodeName = "КРЕП СПИРТ ПО ОБЪЕМ" },
            new OkeiEntry { Code = "831", Name = "Литр чистого (100%) спирта", ShortName = "л 100% спирта", CodeName = "Л ЧИСТ СПИРТ" },
            new OkeiEntry { Code = "833", Name = "Гектолитр чистого (100%) спирта", ShortName = "Гл 100% спирта", CodeName = "ГЛ ЧИСТ СПИРТ" },
            new OkeiEntry { Code = "841", Name = "Килограмм пероксида водорода", ShortName = "кг H2О2", CodeName = "КГ ПЕРОКСИД ВОДОРОДА" },
            new OkeiEntry { Code = "845", Name = "Килограмм 90%-го сухого вещества", ShortName = "кг 90% с/в", CodeName = "КГ 90 ПРОЦ СУХ ВЕЩ" },
            new OkeiEntry { Code = "847", Name = "Тонна 90%-го сухого вещества", ShortName = "т 90% с/в", CodeName = "Т 90 ПРОЦ СУХ ВЕЩ" },
            new OkeiEntry { Code = "852", Name = "Килограмм оксида калия", ShortName = "кг К2О", CodeName = "КГ ОКСИД КАЛИЯ" },
            new OkeiEntry { Code = "859", Name = "Килограмм гидроксида калия", ShortName = "кг КОН", CodeName = "КГ ГИДРОКСИД КАЛИЯ" },
            new OkeiEntry { Code = "861", Name = "Килограмм азота", ShortName = "кг N", CodeName = "КГ АЗОТ" },
            new OkeiEntry { Code = "863", Name = "Килограмм гидроксида натрия", ShortName = "кг NaOH", CodeName = "КГ ГИДРОКСИД НАТРИЯ" },
            new OkeiEntry { Code = "865", Name = "Килограмм пятиокиси фосфора", ShortName = "кг Р2О5", CodeName = "КГ ПЯТИОКИСЬ ФОСФОРА" },
            new OkeiEntry { Code = "867", Name = "Килограмм урана", ShortName = "кг U", CodeName = "КГ УРАН" }
        };


       
    }
}
